export const spells = {
  SBB_SPELL_SHARDOFTHEICEQUEEN: { name: 'Shard of the Ice Queen' },
  SBB_SPELL_FORBIDDENFRUIT: { name: 'Forbidden Fruit' },
  SBB_SPELL_SHRINKRAY: { name: 'Shrink Ray' },
  SBB_SPELL_FREEROLL: { name: 'Free Roll' },
  SBB_SPELL_TESTYOURMIGHT: { name: 'Magic Research' },
  SBB_SPELL_EENIEMEENIEMINEYMO: { name: 'Roll the Dice' },
  SBB_SPELL_SUGARANDSPICE: { name: 'Sugar and Spice' },
  "SBB_SPELL_WITCH'SBREW": { name: "Witch's Brew" },
  SBB_SPELL_FORGLORY: { name: 'For Glory!' },
  SBB_SPELL_MYSTERIOUSSCROLL: { name: "Genie's Wish" },
  SBB_SPELL_TRANSFORMATION: { name: "True Love's Kiss" },
  SBB_SPELL_DRINKMEPOTION: { name: "Luna's Grace" },
  SBB_SPELL_BLESSEDTOME: { name: 'Turkish Delight' },
  SBB_SPELL_TOMEOFKNOWLEDGE: { name: 'Wish Upon a Star' },
  SBB_SPELL_GINGERBREADPARTY: { name: 'Gingerbread Party' },
  SBB_SPELL_FALLINGSTARS: { name: 'Falling Stars' },
  SBB_SPELL_EARTHQUAKE: { name: 'Earthquake' },
  SBB_SPELL_SAPMAGIC: { name: 'Flourish' },
  SBB_SPELL_MONSTERMASH: { name: 'Worm Root' },
  "SBB_SPELL_BELLE'SINFLUENCE": { name: "Beauty's Influence" },
  SBB_SPELL_KIDNAP: { name: 'Kidnap' },
  "SBB_SPELL_MAGE'SCANTRIP": { name: 'Healing Potion' },
  SBB_SPELL_FULLMOON: { name: 'Potion of Heroism' },
  SBB_SPELL_CANDYRAIN: { name: 'Candy Rain' },
  SBB_SPELL_WRINKLEINTIME: { name: 'Mixawizzle' },
  SBB_SPELL_FLAMINGAURA: { name: 'Burning Palm' },
  SBB_SPELL_STONESKIN: { name: 'Stoneskin' },
  SBB_SPELL_FEEDTHEKRAKEN: { name: 'Feed the Kraken' },
  SBB_SPELL_RIDEOFTHEVALKYRIES: { name: 'Ride of the Valkyries' },
  SBB_SPELL_POTIONOFHEROISM: { name: "Merlin's Test" },
  SBB_SPELL_ROYALPOWER: { name: "Queen's Grace" },
  SBB_SPELL_SEVENDWARVES: { name: 'Hi Ho!' },
  SBB_SPELL_MENAGERIE: { name: 'Toil and Trouble' },
  SBB_SPELL_LIGHTNINGBOLT: { name: 'Lightning Bolt' },
  SBB_SPELL_FIREBALL: { name: 'Fireball' },
  "SBB_SPELL_ANGEL'SBLESSING": { name: 'Blessing of Athena' },
  SBB_SPELL_FARFARAWAY: { name: 'The End' },
  SBB_SPELL_BEASTWITHIN: { name: "Cat's Call" },
  SBB_SPELL_HERMESMAGICBEANS: { name: "Hermes' Magic Beans" },
  SBB_SPELL_BLAZEOFGLORY: { name: 'Blaze of Glory' },
  SBB_SPELL_POISONAPPLE: { name: 'Poison Apple' },
  SBB_SPELL_LUCKYCOIN: { name: 'Lucky Coin' },
  SBB_SPELL_CROCBAIT: { name: 'Croc Bait' },
  SBB_SPELL_GIGANTIFY: { name: 'Gigantify' },
  SBB_SPELL_HUGIFY: { name: 'Hugeify' },
  SBB_SPELL_KNIGHTHOOD: { name: 'Knighthood' },
  SBB_SPELL_EVILTWIN: { name: 'Evil Twin' },
  SBB_SPELL_DISINTEGRATE: { name: 'Smite' },
  SBB_SPELL_PIGOMORPH: { name: 'Pigomorph' },
  SBB_SPELL_FOG: { name: 'Fog' },
  SBB_SPELL_DIVINATION: { name: 'Drink Me Potion' },
  SBB_SPELL_MASTERDISGUISE: { name: 'It Was All a Dream' },
}
export const treasures = {
  SBB_TREASURE_RUSTYDAGGERS: { name: 'Needle Nose Daggers' },
  SBB_TREASURE_RUNESTONES: { name: 'Rune Stones' },
  SBB_TREASURE_LOCKEDCHEST: { name: 'Locked Chest' },
  SBB_TREASURE_RINGOFREGENERATION: { name: 'Ring of Regeneration' },
  "SBB_TREASURE_JACK'SJUMPINGBEANS": { name: "Jack's Jumping Beans" },
  SBB_TREASURE_SPINNINGWHEEL: { name: 'Spinning Wheel' },
  "SBB_TREASURE_SHEPHERD'SSLING": { name: "Shepherd's Sling" },
  SBB_TREASURE_CORRUPTEDHEARTWOOD: { name: 'Corrupted Heartwood' },
  SBB_TREASURE_CROWNOFATLAS: { name: 'Crown of Atlas' },
  SBB_TREASURE_TRAININGDUMMY: { name: 'Fairy Tail' },
  "SBB_TREASURE_HERMES'BOOTS": { name: "Hermes' Boots" },
  SBB_TREASURE_PIGGIEBANK: { name: 'Piggie Bank' },
  SBB_TREASURE_BOUNTYBOARD: { name: 'Bounty Board' },
  SBB_TREASURE_MONSTERMANUAL: { name: 'Monster Manual' },
  SBB_TREASURE_SECRETSTASH: { name: 'Secret Stash' },
  SBB_TREASURE_BOOKOFHEROES: { name: 'Book of Heroes' },
  SBB_TREASURE_DEVILSCONTRACT: { name: 'Dark Contract' },
  SBB_TREASURE_RINGOFMETEORS: { name: 'Ring of Meteors' },
  SBB_TREASURE_DRAGONNEST: { name: 'Dragon Nest' },
  SBB_TREASURE_QUESTINGPET: { name: 'Noble Steed' },
  SBB_TREASURE_SHARPENINGSTONE: { name: 'Dancing Sword' },
  SBB_TREASURE_FOUNTAINOFYOUTH: { name: 'Fountain of Youth' },
  SBB_TREASURE_POTIONCAULDRON: { name: "Potion Master's Cookbook" },
  SBB_TREASURE_GREATLIBRARYCARD: { name: "Merlin's Slippers" },
  SBB_TREASURE_SKIPSPUZZLECUBE: { name: "Skip's Puzzle Rune" },
  SBB_TREASURE_STING: { name: 'Sting' },
  SBB_TREASURE_TELLTALEQUIVER: { name: 'Tell Tale Quiver' },
  SBB_TREASURE_ANCIENTSARCOPHAGUS: { name: 'Ancient Sarcophagus' },
  SBB_TREASURE_STONEHELM: { name: 'Haunted Helm' },
  SBB_TREASURE_FANCYPANTS: { name: 'Fancy Pants' },
  SBB_TREASURE_BOUNTIFULMINE: { name: 'Deepstone Mine' },
  SBB_TREASURE_SUPERRUNESTONES: { name: 'Treasure Map' },
  SBB_TREASURE_EYESOFARES: { name: 'Eye of Ares' },
  SBB_TREASURE_RINGOFREVENGE: { name: 'Ring of Thunder' },
  SBB_TREASURE_BADMOON: { name: 'Bad Moon' },
  SBB_TREASURE_POWERSTONE: { name: 'Power Orb' },
  SBB_TREASURE_CLOAKOFTHEASSASSIN: { name: 'Cloak of the Assassin' },
  "SBB_TREASURE_MERLIN'SHAT": { name: "Merlin's Hat" },
  SBB_TREASURE_CRYSTALBALL: { name: 'Crystal Ball' },
  SBB_TREASURE_CURSEDTHRONE: { name: 'Cursed Throne' },
  SBB_TREASURE_SKYCASTLE: { name: 'Sky Castle' },
  "SBB_TREASURE_MONKEY'SPAW": { name: 'Coin of Charon' },
  SBB_TREASURE_GLOVESOFTHIEVING: { name: 'Gloves of Thieving' },
  SBB_TREASURE_REDUPLICATOR: { name: 'Reduplicator' },
  "SBB_TREASURE_FOOL'SGOLD": { name: "Fool's Gold" },
  SBB_TREASURE_COMPACTMIRROR: { name: 'Forking Rod' },
  SBB_TREASURE_SURGINGSTONE: { name: 'Ring of Rage' },
  SBB_TREASURE_RINGOFDISCIPLINE: { name: 'Six of Shields' },
  SBB_TREASURE_DECKOFMANYTHINGS: { name: 'Deck of Many Things' },
  SBB_TREASURE_POWERGEM: { name: 'Moonsong Horn' },
  SBB_TREASURE_SUMMONINGCIRCLE: { name: 'Summoning Portal' },
  SBB_TREASURE_BANNEROFCOMMAND: { name: 'Horn of Olympus' },
  SBB_TREASURE_PIRATESHIP: { name: "Krampus' Sleigh" },
  SBB_TREASURE_SWORDOFFIREANDICE: { name: 'Sword of Fire and Ice' },
  SBB_TREASURE_AMBROSIA: { name: 'Ambrosia' },
  "SBB_TREASURE_DRACULA'SSABER": { name: "Dracula's Saber" },
  SBB_TREASURE_MIDASHAND: { name: 'Hand of Midas' },
  SBB_TREASURE_SCROLLOFTHEELDERS: { name: 'Staff of the Old Toad' },
  SBB_TREASURE_HELMOFCOMMAND: { name: 'Evil Eye' },
  SBB_TREASURE_HEXINGWAND: { name: "Monkey's Paw" },
  SBB_TREASURE_SPEAROFACHILLES: { name: 'Spear of Achilles' },
  SBB_TREASURE_EMBIGGININGSTONE: { name: 'Embiggening Stone' },
  SBB_TREASURE_ELDERWAND: { name: 'Wand of Weirding' },
  SBB_TREASURE_WHIRLINGBLADES: { name: 'The Singing Sword' },
  SBB_TREASURE_IVORYOWL: { name: 'Ivory Owl' },
  SBB_TREASURE_DRAGONSHOARD: { name: "Pandora's Box" },
  SBB_TREASURE_THEARK: { name: 'The Ark' },
  SBB_TREASURE_PHOENIXFEATHER: { name: 'Phoenix Feather' },
  SBB_TREASURE_THENINTHBOOKOFMERLIN: { name: 'The 9th Book of Merlin' },
  SBB_TREASURE_TREASURECHEST: { name: 'Mimic' },
  SBB_TREASURE_THEROUNDTABLE: { name: 'The Round Table' },
  SBB_TREASURE_BLACKPRISM: { name: 'Black Prism' },
  SBB_TREASURE_EXCALIBUR: { name: 'Excalibur' },
  SBB_TREASURE_THEHOLYGRAIL: { name: 'The Holy Grail' },
  SBB_TREASURE_MIRRORUNIVERSE: { name: 'Mirror Mirror' },
  SBB_TREASURE_FAIRYQUEENSWAND: { name: "Fairy Queen's Wand" },
  'SBB_TREASURE_MAGICSWORD+100': { name: 'Magic Sword +100' },
  SBB_TREASURE_RADIANTPRISM: { name: 'The World Tree' },
}
export const heroes = {
  SBB_HERO_MRSCLAUS: { name: 'Mrs. Claus' },
  SBB_HERO_KRAMPUS: { name: 'Krampus' },
  SBB_HERO_GEPETTO: { name: 'Geppetto' },
  SBB_HERO_GANDALF: { name: 'Pup the Magic Dragon' },
  'SBB_HERO_SIRPIPS-A-LOT': { name: "Jack's Giant" },
  SBB_HERO_HORDEDRAGON: { name: 'Hoard Dragon' },
  SBB_HERO_FATE: { name: 'The Fates' },
  SBB_HERO_MERLIN: { name: 'Merlin' },
  SBB_HERO_MUERTE: { name: 'Muerte' },
  SBB_HERO_MORDRED: { name: 'Mordred' },
  SBB_HERO_MADCATTER: { name: 'Mad Catter' },
  SBB_HERO_THEGREEDCURSED: { name: 'The Cursed King' },
  SBB_HERO_PRINCESSBELLE: { name: 'Beauty' },
  SBB_HERO_POTIONMASTER: { name: 'Potion Master' },
  SBB_HERO_PETERPAN: { name: 'Peter Pants' },
  SBB_HERO_DARKONE: { name: 'Evella' },
  SBB_HERO_PIEDPIPER: { name: 'Pied Piper' },
  SBB_HERO_DRACULA: { name: 'Sad Dracula' },
  SBB_HERO_GWEN: { name: 'Gwen' },
  SBB_HERO_MORGANLEFAY: { name: 'Morgan le Fay' },
  SBB_HERO_CARDCHEAT: { name: "Pan's Shadow" },
  SBB_HERO_OLDGRANNY: { name: 'Grandmother' },
  'SBB_HERO_SKIP,THETIMESKIPPER': { name: 'Skip, The Time Skipper' },
  SBB_HERO_BIGDEAL: { name: 'Xelhua' },
  SBB_HERO_CHARON: { name: 'Charon' },
  SBB_HERO_SIRGALAHAD: { name: 'Sir Galahad' },
  SBB_HERO_LOKI: { name: 'Loki' },
  SBB_HERO_THECOLLECTOR: { name: 'Celestial Tiger' },
  SBB_HERO_MAIDMARIAN: { name: 'Snow Angel' },
  SBB_HERO_MASK: { name: 'Mask' },
  SBB_HERO_MILITARYLEADER: { name: 'Trophy Hunter' },
  SBB_HERO_WONDERWADDLE: { name: 'Wonder Waddle' },
  SBB_HERO_FALLENANGEL: { name: 'Fallen Angel' },
  SBB_HERO_KINGLION: { name: 'Mihri, King Lion' },
  SBB_HERO_BLACKKNIGHT: { name: 'The Headless Horseman' },
  SBB_HERO_APOCALYPSE: { name: 'Apocalypse' },
  SBB_HERO_KINGMIDAS: { name: 'King Midas' },
  SBB_HERO_SHAREBEAR: { name: 'Sharebear' },
  SBB_HERO_SEER: { name: 'The Sphinx' },
}
export const characters = {
  SBB_CHARACTER_FROGPRINCE: { name: `Frog Prince` },
  SBB_CHARACTER_SHEEP: { name: `Sheep`, attack: 1, defense: 1 },
  SBB_CHARACTER_SHEEP_GOLDEN: { name: `Sheep`, attack: 2, defense: 2 },
  SBB_CHARACTER_TWEEDLEDUM: { name: `Tweedle Dum`, attack: 0, defense: 0 },
  SBB_CHARACTER_PIG: { name: `Pig`, attack: 10, defense: 10 },
  SBB_CHARACTER_STATUE: { name: `Statue`, attack: 0, defense: 6 },
  SBB_CHARACTER_GOLDENSTATUE: { name: `Statue`, attack: 0, defense: 3 },
  SBB_CHARACTER_AWOKENPRINCESS: {
    name: `Awoken Princess`,
    attack: 8,
    defense: 8,
  },
  SBB_CHARACTER_CAT: { name: `Cat`, attack: 1, defense: 1 },
  SBB_CHARACTER_CAT_GOLDEN: { name: `Cat`, attack: 2, defense: 2 },
  SBB_CHARACTER_EVILWOLF: { name: `Evil Sheep`, attack: 6, defense: 6 },
  SBB_CHARACTER_EVILWOLF_GOLDEN: {
    name: `Evil Sheep`,
    attack: 12,
    defense: 12,
  },
  SBB_CHARACTER_PIGGY: { name: `Big Pig`, attack: 3, defense: 3 },
  SBB_CHARACTER_PIGGY_GOLDEN: { name: `Big Pig`, attack: 6, defense: 6 },
  SBB_CHARACTER_PAPABEAR: { name: `Papa Bear`, attack: 4, defense: 4 },
  SBB_CHARACTER_PAPABEAR_GOLDEN: { name: `Papa Bear`, attack: 8, defense: 8 },
  SBB_CHARACTER_MAMABEAR: { name: `Mama Bear`, attack: 6, defense: 6 },
  SBB_CHARACTER_MAMABEAR_GOLDEN: { name: `Mama Bear`, attack: 12, defense: 12 },
  SBB_CHARACTER_CAPTAINCROC: { name: `Captain Croc`, attack: 10, defense: 10 },
  TST_CHARACTER_TEST_DUMMY: { name: `Test Dummy`, attack: 1, defense: 1 },
  SBB_CHARACTER_WEEWILLIEWINKIE: { name: `Tiny`, attack: 6, defense: 1 },
  SBB_CHARACTER_BADBILLYGRUFF: {
    name: `B-a-a-d Billy Gruff`,
    attack: 2,
    defense: 3,
  },
  SBB_CHARACTER_FRIENDLYTREE: {
    name: `Happy Little Tree`,
    attack: 1,
    defense: 1,
  },
  SBB_CHARACTER_CATBURGLAR: { name: `Kitty Cutpurse`, attack: 1, defense: 1 },
  SBB_CHARACTER_BABYDRAGON: { name: `Baby Dragon`, attack: 3, defense: 2 },
  SBB_CHARACTER_MADMADAMMIM: { name: `Mad Mim`, attack: 0, defense: 3 },
  SBB_CHARACTER_BABYROOT: { name: `Baby Root`, attack: 0, defense: 3 },
  SBB_CHARACTER_BLACKCAT: { name: `Black Cat`, attack: 1, defense: 1 },
  SBB_CHARACTER_BIGBOSS: { name: `Bossy`, attack: 2, defense: 2 },
  SBB_CHARACTER_LONELYPRINCE: { name: `Lonely Prince`, attack: 1, defense: 1 },
  "SBB_CHARACTER_WIZARD'SFAMILIAR": {
    name: `Wizard's Familiar`,
    attack: 1,
    defense: 1,
  },
  SBB_CHARACTER_FOXTAILARCHER: {
    name: `Sherwood Sureshot`,
    attack: 2,
    defense: 1,
  },
  SBB_CHARACTER_HUMPTYDUMPTY: { name: `Humpty Dumpty`, attack: 7, defense: 7 },
  SBB_CHARACTER_LABYRINTHMINOTAUR: {
    name: `Labyrinth Minotaur`,
    attack: 5,
    defense: 1,
  },
  SBB_CHARACTER_HELPFULGODMOTHER: {
    name: `Rainbow Unicorn`,
    attack: 1,
    defense: 5,
  },
  'SBB_CHARACTER_CINDER-ELLA': { name: `Cinder-Ella`, attack: 2, defense: 2 },
  SBB_CHARACTER_BLINDMOUSE: { name: `Blind Mouse`, attack: 2, defense: 2 },
  SBB_CHARACTER_DWARVENARTIFICER: { name: `Crafty`, attack: 2, defense: 2 },
  SBB_CHARACTER_THETOOTHFAIRY: {
    name: `Golden Chicken`,
    attack: 2,
    defense: 2,
  },
  SBB_CHARACTER_POLYWOGGLE: { name: `Polywoggle`, attack: 1, defense: 1 },
  SBB_CHARACTER_THEWHITESTAG: { name: `The White Stag`, attack: 3, defense: 3 },
  SBB_CHARACTER_QUESTINGPRINCESS: {
    name: `Brave Princess`,
    attack: 5,
    defense: 3,
  },
  SBB_CHARACTER_TROJANDONKEY: { name: `Trojan Donkey`, attack: 2, defense: 6 },
  SBB_CHARACTER_PRINCESSPEEP: { name: `Princess Peep`, attack: 1, defense: 1 },
  SBB_CHARACTER_ROMEO: { name: `Romeo`, attack: 5, defense: 3 },
  SBB_CHARACTER_QUEENOFHEARTS: {
    name: `Queen of Hearts`,
    attack: 1,
    defense: 1,
  },
  SBB_CHARACTER_WICKEDWITCHOFTHEWEST: {
    name: `Wicked Witch of the West`,
    attack: 3,
    defense: 2,
  },
  SBB_CHARACTER_GOODWITCHOFTHENORTH: {
    name: `Good Witch of the North`,
    attack: 2,
    defense: 3,
  },
  SBB_CHARACTER_LUCKY: { name: `Lucky`, attack: 3, defense: 2 },
  SBB_CHARACTER_TIM: { name: `Spell Weaver`, attack: 1, defense: 3 },
  SBB_CHARACTER_SHADOWASSASSIN: {
    name: `Shadow Assassin`,
    attack: 2,
    defense: 4,
  },
  SBB_CHARACTER_SLEEPINGPRINCESS: {
    name: `Sleeping Princess`,
    attack: 0,
    defense: 8,
  },
  SBB_CHARACTER_DARKWOODCREEPER: {
    name: `Darkwood Creeper`,
    attack: 0,
    defense: 3,
  },
  SBB_CHARACTER_MONSTAR: { name: `Ogre Princess`, attack: 4, defense: 2 },
  SBB_CHARACTER_DUMBLEDWARF: { name: `Dubly`, attack: 2, defense: 2 },
  SBB_CHARACTER_PRIZEDPIG: { name: `Prized Pig`, attack: 3, defense: 6 },
  SBB_CHARACTER_NIGHTSTALKER: { name: `Vain-Pire`, attack: 4, defense: 4 },
  SBB_CHARACTER_PRINCESSNIGHT: {
    name: `Princess Wight`,
    attack: 3,
    defense: 5,
  },
  SBB_CHARACTER_WRETCHEDMUMMY: {
    name: `Wretched Mummy`,
    attack: 2,
    defense: 1,
  },
  SBB_CHARACTER_WATERWRAITH: { name: `Water Wraith`, attack: 3, defense: 3 },
  SBB_CHARACTER_JULIET: { name: `Juliet`, attack: 7, defense: 7 },
  SBB_CHARACTER_LADYOFTHELAKE: {
    name: `Lady of the Lake`,
    attack: 3,
    defense: 3,
  },
  SBB_CHARACTER_MAGEMASTER: { name: `Sporko`, attack: 3, defense: 3 },
  SBB_CHARACTER_ELDERTREANT: { name: `Heartwood Elder`, attack: 5, defense: 7 },
  SBB_CHARACTER_THECHUPACABRA: {
    name: `The Chupacabra`,
    attack: 8,
    defense: 6,
  },
  SBB_CHARACTER_LIGHTNINGDRAGON: {
    name: `Lightning Dragon`,
    attack: 10,
    defense: 1,
  },
  SBB_CHARACTER_COURTWIZARD: { name: `Court Wizard`, attack: 4, defense: 2 },
  SBB_CHARACTER_RIVERWISHMERMAID: {
    name: `Riverwish Mermaid`,
    attack: 4,
    defense: 8,
  },
  SBB_CHARACTER_MEDUSA: { name: `Medusa`, attack: 3, defense: 3 },
  SBB_CHARACTER_VULTURE: { name: `Bearded Vulture`, attack: 3, defense: 3 },
  SBB_CHARACTER_GOLDENGOOSE: { name: `Greedy`, attack: 5, defense: 9 },
  SBB_CHARACTER_FAIRYGODMOTHER: {
    name: `Fairy Godmother`,
    attack: 4,
    defense: 4,
  },
  SBB_CHARACTER_FRIENDLYGHOST: {
    name: `Friendly Spirit`,
    attack: 3,
    defense: 4,
  },
  SBB_CHARACTER_PUFFPUFF: { name: `Puff Puff`, attack: 7, defense: 7 },
  SBB_CHARACTER_VENGEFULGODMOTHER: {
    name: `The Nutcracker`,
    attack: 4,
    defense: 10,
  },
  SBB_CHARACTER_COPYCAT: { name: `Copycat`, attack: 2, defense: 10 },
  SBB_CHARACTER_HUNGRYHUNGRYHIPPOCAMPUS: {
    name: `Hungry Hungry Hippocampus`,
    attack: 10,
    defense: 1,
  },
  SBB_CHARACTER_KINGARTHUR: { name: `King Arthur`, attack: 5, defense: 5 },
  SBB_CHARACTER_SOLTAKANCIENT: {
    name: `Soltak Ancient`,
    attack: 0,
    defense: 20,
  },
  SBB_CHARACTER_MONSTERBOOK: { name: `Monster Book`, attack: 7, defense: 3 },
  SBB_CHARACTER_GINGERBREADKNIGHT: {
    name: `Gingerbread Knight`,
    attack: 7,
    defense: 7,
  },
  SBB_CHARACTER_FATDRAGON: { name: `Feasting Dragon`, attack: 6, defense: 8 },
  SBB_CHARACTER_LEAPFROG: { name: `Time Flies`, attack: 2, defense: 2 },
  SBB_CHARACTER_AIMY: { name: `Amy`, attack: 6, defense: 6 },
  'SBB_CHARACTER_NIAN,THESEATERROR': {
    name: `Nian, Sea Terror`,
    attack: 10,
    defense: 10,
  },
  SBB_CHARACTER_LANCELOT: { name: `Lancelot`, attack: 9, defense: 9 },
  SBB_CHARACTER_DWARFMINER: { name: `Angry`, attack: 10, defense: 15 },
  SBB_CHARACTER_THREEBIGPIGS: { name: `Three Big Pigs`, attack: 9, defense: 9 },
  SBB_CHARACTER_BABYBEAR: { name: `Baby Bear`, attack: 2, defense: 2 },
  SBB_CHARACTER_TWEEDLEDEE: { name: `Tweedle Dee`, attack: 10, defense: 3 },
  SBB_CHARACTER_LOBO: { name: `Southern Siren`, attack: 10, defense: 10 },
  SBB_CHARACTER_ROTTENAPPLETREE: {
    name: `Rotten Appletree`,
    attack: 0,
    defense: 18,
  },
  SBB_CHARACTER_CUPID: { name: `Cupid`, attack: 1, defense: 10 },
  SBB_CHARACTER_SUMMONER: { name: `Aon`, attack: 6, defense: 12 },
  SBB_CHARACTER_BABAYAGA: { name: `Baba Yaga`, attack: 3, defense: 6 },
  SBB_CHARACTER_GOODANDEVILSISTERS: {
    name: `Shoulder Faeries`,
    attack: 1,
    defense: 1,
  },
  SBB_CHARACTER_WOMBATSINDISGUISE: {
    name: `Wombats in Disguise`,
    attack: 5,
    defense: 5,
  },
  SBB_CHARACTER_ROBINWOOD: { name: `Robin Wood`, attack: 7, defense: 10 },
  SBB_CHARACTER_WORLDSERPENT: { name: `Jormungand`, attack: 20, defense: 20 },
  SBB_CHARACTER_GRUMBLEGORE: { name: `Boom Hilda`, attack: 10, defense: 5 },
  SBB_CHARACTER_THEGREENKNIGHT: {
    name: `The Green Knight`,
    attack: 10,
    defense: 30,
  },
  SBB_CHARACTER_FORGEMASTERDWARF: { name: `Lordy`, attack: 7, defense: 7 },
  SBB_CHARACTER_DOOMBREATH: { name: `Doombreath`, attack: 10, defense: 6 },
  SBB_CHARACTER_HERCULES: { name: `Hercules`, attack: 25, defense: 25 },
  SBB_CHARACTER_ECHOWOODSHAMBLER: { name: `Echowood`, attack: 1, defense: 1 },
  SBB_CHARACTER_BURNINGTREE: { name: `Burn Beard`, attack: 4, defense: 20 },
  SBB_CHARACTER_GOODBOY: { name: `Good Boy`, attack: 2, defense: 2 },
  SBB_CHARACTER_THEGREATANDPOWERFUL: {
    name: `Scion of the Storm`,
    attack: 2,
    defense: 2,
  },
  SBB_CHARACTER_KINGTREE: { name: `Ashwood Elm`, attack: 0, defense: 15 },
  SBB_CHARACTER_PROSPERO: { name: `Bearstine`, attack: 7, defense: 10 },
  SBB_CHARACTER_PUMPKINKING: {
    name: `The Great Pumpkin`,
    attack: 10,
    defense: 10,
  },
  SBB_CHARACTER_MONSTERLORD: { name: `Oni Tyrant`, attack: 13, defense: 13 },
  SPK_CHARACTER_PRINCESSPEA: { name: `Empress Pea`, attack: 10, defense: 10 },
}

function invert(cards) {
  return Object.entries(cards).reduce(
    (acc, [id, { name }]) => ({
      ...acc,
      [name.replaceAll(' ', '')]: id,
    }),
    {},
  )
}
export const charIDMap = invert(characters)
export const treasureIDMap = invert(treasures)
export const heroIDMap = invert(heroes)
export const spellsIDMap = invert(spells)
